### ISSUE TITLE
[$injector:nomod] Module 'angular-timepicker' is not available! While Iam trying to inject to MeanJs app.Is dependency naming Convention (angular-timepicker) is Correct ?

### ISSUE THREAD

**Issue by prasad47** [Geta/angular-timepicker#17]
Hi,
Your angular-time picker is really Nice  ..i installed Via Bower 
1. I did bower install angular-timepicker.
2. added file to my project all.js@ Meanjs Project.
3. Injected Dependency to my Main Module With Name ['angular-timepicker'].

which is causing Error :- 
[$injector:modulerr] Failed to instantiate module angular-timePicker due to:
[$injector:nomod] Module 'angular-timePicker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.28/$injector/nomod?p0=angular-timePicker

Thanks,
Prasad.

**Comment by dnasir** [comment]
@prasad47 The module name is dnTimepicker. I should probably rename it, but it is what it is. At least for now ;-)

**Comment by prasad47** [comment]
Sure ... Thank You !!
