### ISSUE TITLE
Updated time not showing

### ISSUE THREAD

**Issue by cshinaver** [Geta/angular-timepicker#22]
I've been trying to integrate this into my project for a little while now and can't seem to figure out this issue. Whenever I click on the field, the dropdown of times shows up, but selecting an individual time does not change the displayed time in the field. I also downloaded the demo app and was having the same issue there as well.

**Comment by dnasir** [comment]
Thanks for letting me know. I'll have a look at it.

**Comment by matthewtmoran** [comment]
I am looking at using this for my project and noticed this issue.  I think it has to do with the blur event.  around line ~240.  I removed it and so far seem to be getting proper results.  I'm not sure what the consequences might be though.

**Comment by matthewtmoran** [comment]
Ah, I see that the blur event was to enable the close event when a user tabs out.  To keep this functionality in tact I wrapped the call to the close event in the blur method in $timeout and added a very slight delay.  Probably not the best solution but it works for now...

**Comment by rrhanson** [comment]
I fixed this in a fork by removing the blur event that was added in by a previously merged PR, and listening for keydown of tab or esc to close the popup. Looks like another fork (by cwhenderson20) fixed this the same way. 

My fork has deviated a bit, as I have removed the dependency on ui bootstrap and made a few other modifications to the behavior of typing in times. Maybe you can take what you want from it or I could make a pull request with what I have in the fork?

https://github.com/rrhanson/angular-timepicker

**Comment by dnasir** [comment]
@rrhanson Feel free to submit a PR.
