### ISSUE TITLE
Timepicker dropdown is not displaying values

### ISSUE THREAD

**Issue by pradt** [Geta/angular-timepicker#25]
Hi, 
Thanks for your directive, its perfect for what I'm looking for. 

I've loaded everything that I needed according what has been specified in GitHub (Angular version 1.5.8, Angular Bootstrap, Dateparser). 

The element that I'm using is straight from the example : 

`test: <input type="text" dn-timepicker="h:mm a" min-time="00:00" max-time="23:59" step="15" ng-model="timepicker.model" />`

In my controller I did the following to setup the model : 

```
$scope.timepicker = {
            model: new Date()
        };
```

So when the page loads it displays the textbox element and the current time. However, when I click on the element a small element being displayed, but without any values. I checked the Inspector in Chrome and I can see the style change, but the unordered list doesn't contain any values. 

I'm not sure what I need to do display the list of values. 

Also, I'm planning to do a range of time (i.e two boxes) I'm assuming that I can set the min/max from each of the controls (I haven't tried it yet, but would that work )?

**Comment by dnasir** [comment]
Have you tested this with an older version of Angular?
