### ISSUE TITLE
Ionic Pattern value mismatch and Invalid hours in console

### ISSUE THREAD

**Issue by ukenpachi** [Geta/angular-timepicker#26]
Hi, I am using the demo example from [dnasir.com](http://www.dnasir.com/2013/12/06/angular-timepicker-directive/) 

**Setting up**
_Angular 1.5.3
Ionic 1.3.3. framework_

I have added the modules 

 _ui.bootstrap.position_ **and**  _dnTimepicker_
and on my html added 

`<input type="text" dn-timepicker ng-model="time1" min-time="9:00" max-time="17:00" step="10m" time-format="HH:mm" />`
and controller, I have 

`$scope.time1 = new Date();`

Any idea why this is? Thanks

**Comment by ukenpachi** [comment]
` <input type="text" dn-timepicker ng-model="time1" />` works on it own but I need those options max-time, min-time, step and time-format.

**Comment by dnasir** [comment]
@ukenpachi That's strange. You code should work fine. Can you set up a fiddle or a plunker so I can test your code?

**Comment by ukenpachi** [comment]
@dnasir sorry I took too long to reply but here is it [Plnkr](http://plnkr.co/edit/ycKMbCvteHVacjuANDK3?p=preview). I just copied your code from the demo in [dnasir.com](http://www.dnasir.com/2013/12/06/angular-timepicker-directive/). It seems that your code does not work in angular js 1.5.3 which is what I am using but work in versions 1.2.0 which is what the demo is using.

**Comment by dnasir** [comment]
@ukenpachi I might be missing something, but the angular.timepicker.js file that you included in the demo looks different to the one in the repo. The original code depends on a separate module called [angular-dateParser](https://github.com/dnasir/angular-dateParser) but the one in your code doesn't seem to have this dependency. Did you make any changes to the original code?

**Comment by ukenpachi** [comment]
@dnasir thank for the reply. I just copied and paste what your code file from the demo. I did no change anything apart from adding ionic 1.3.3 which uses angular 1.5.3. So if you could please create a plnkr using the ionic version in my current plnkr above. It will be great. Thank you

**Comment by dnasir** [comment]
@ukenpachi I've updated your plunk, and fixed a small bug where clicking on a value doesn't update the model. This was most likely introduced by one of the merge commits. I'll apply the fix to the master branch shortly and will release a fixed version soon.

http://plnkr.co/edit/ojXPGXCwzfwxTIkljId9

**Comment by ukenpachi** [comment]
Thanks @dnasir highly appreciate it :)

**Comment by ukenpachi** [comment]
Please comment here when you update the master branch, so I can pull. Thanks

**Comment by ukenpachi** [comment]
@dnasir hi, I was wondering when will you update the repo? Thanks

**Comment by dnasir** [comment]
Updated! https://github.com/Geta/angular-timepicker/releases/tag/1.0.11

**Comment by ukenpachi** [comment]
thank you
