### ISSUE TITLE
Time can not select due to blur event

### ISSUE THREAD

**Issue by premchandrasingh** [Geta/angular-timepicker#27]
Hi,
It seems to be the `blur` event is closing the popup and not allowing to select a value by using mouse. Here is the [plnkr](https://plnkr.co/edit/TDu6XGChDCcaQoKh6Q6e?p=preview). I copied the code from dist folder and comment out the close popup statement inside the blur event.

It will be nice to have
- A configurable null item as placeholder, which people frequently used like -Select-, -None- etc
- When popup opens up, the model value get selected in the popup
- Keyedown does not start selection from very first without the input of mouse

May be I will do in a fork version.

**Comment by premchandrasingh** [comment]
I just notice it is all working fine in the demo.html.

**Comment by premchandrasingh** [comment]
I just notice second point is working on demo.html

**Comment by dnasir** [comment]
@premchandrasingh 

Good catch. I'll fix it when I have time, but feel free to submit a PR.

> A configurable null item as placeholder, which people frequently used like -Select-, -None- etc

You can use the ``placeholder`` attribute for this.

> When popup opens up, the model value get selected in the popup

I'm not sure I follow. Can you explain this further? An example would help tremendously.

> Keyedown does not start selection from very first without the input of mouse

You can tab into the input, and keyboard UP/DOWN should allow you to navigate the list. Or, I misunderstood your question?
